name: "Pull Request Labeler"
on:
- pull_request_target

permissions:
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Apply Type Label
        uses: actions/labeler@v3
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: ""  # works around actions/labeler#104
