name: CI

on:
  push:
  pull_request:
    branches:
      - '*'
  workflow_dispatch:
    inputs:
      version:
        description: Release Version
        required: false

# Builds & Uploads:
# * Linux x86_64 Portable
# * Linux App Image
# * Mac Universal Portable
# * Mac Universal DMG
# * Windows x86_64 Portable
# * Windows x86_64 Installer
jobs:
  # Checks to see if we have an input, and stamps that onto the repo.
  # Determines if this is a release, and determines the official ref.
  version:
    name: Compute Version & Check for Release
    runs-on: ubuntu-latest
    outputs:
      release: ${{ steps.check_release.outputs.release }}
      ref: ${{ steps.check_release.outputs.ref }}
    steps:
      - name: Update Tag
        uses: richardsimko/update-tag@v1
        if: ${{ github.event.inputs.version }}
        with:
          tag_name: ${{ github.event.inputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Check Release
        id: check_release
        run: |
          export REF=`git describe --match v[0-9]* HEAD --tags`
          echo "Build Version: $REF"
          [[ "$REF" != "" ]] && echo "ref=$REF" >> $GITHUB_OUTPUT
          if [[ `git describe --exact-match --match v[0-9]* HEAD --tags` ]]; then
            echo "release=$REF" >> $GITHUB_OUTPUT
            echo "Release Version: $REF"
          fi
  build_linux:
    name: Linux
    needs: [version]
    runs-on: ubuntu-latest
    container: ghcr.io/lite-xl/lite-xl-build-box:latest
    strategy:
      matrix:
        config:
        - { name: "GCC", cc: gcc, cxx: g++ }
        - { name: "clang", cc: clang, cxx: clang++ }
    env:
      CC: ${{ matrix.config.cc }}
      CXX: ${{ matrix.config.cxx }}
      ARCH: x86_64
    steps:
      - name: System Information
        run: |
          bash --version
          $CC -v
      - name: Set Environment Variables
        run: |
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
          echo "INSTALL_NAME=lite-xl-${{ needs.version.outputs.ref }}-$ARCH-linux" >> "$GITHUB_ENV"
      - uses: actions/checkout@v3
      - name: Build
        run: |
          scripts/build.sh --forcefallback --portable --addons --debug
      - name: Package Portable
        run: |
          tar -zcvf $INSTALL_NAME.tar.gz -C build-$ARCH-linux lite-xl
      - name: Package AppImg
        run: |
          scripts/package-appimage.sh --debug --version ${{ needs.version.outputs.ref }}
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        if: ${{ matrix.config.cc == 'gcc' }}
        with:
          name: Linux Portable & AppImage
          path: |
            *.tar.gz
            *.AppImage

  build_macos:
    name: macOS
    needs: [version]
    runs-on: macos-11
    strategy:
      matrix:
        config:
          - {type: bundle}
          - {type: portable}
    env:
      CC: clang
      CXX: clang++
      ARCHES: x86_64 aarch64
    steps:
      - name: System Information
        run: |
          system_profiler SPSoftwareDataType
          bash --version
          gcc -v
          xcodebuild -version
      - name: Set Environment Variables
        run: |
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
          echo "INSTALL_PREFIX=lite-xl-${{ needs.version.outputs.ref }}" >> "$GITHUB_ENV"
          echo "TYPE=${{ matrix.config.type }}" >> "$GITHUB_ENV"
      - uses: actions/checkout@v3
      - name: Python Setup
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install Dependencies
        run: scripts/install-dependencies.sh --debug
      - name: Build x86_64
        run: |
          scripts/build.sh --addons --debug --forcefallback --$TYPE -b build-lite-xl-x86_64-$TYPE
      - name: Build aarch64
        run: |
          scripts/build.sh --addons --debug --forcefallback --cross-arch aarch64 --$TYPE -b build-lite-xl-aarch64-$TYPE
      - name: Create Universal Binary
        run: |
          mkdir build-lite-xl-$TYPE
          cp -r build-lite-xl-x86_64-$TYPE/lite-xl build-lite-xl-$TYPE/lite-xl
          rm build-lite-xl-$TYPE/lite-xl/lite-xl
          lipo -create -output build-lite-xl-$TYPE/lite-xl/lite-xl build-lite-xl-x86_64-$TYPE/lite-xl/lite-xl build-lite-xl-aarch64-$TYPE/lite-xl/lite-xl
      - name: Package Portable
        if: ${{ matrix.config.type == 'portable' }}
        run: |
          tar -zcvf $INSTALL_PREFIX-macos.tar.gz -C build-lite-xl-portable lite-xl
      - name: Package DMG
        if: ${{ matrix.config.type == 'bundle' }}
        run: |
          cp build-lite-xl-x86_64-bundle/Info.plist build-lite-xl-bundle/Info.plist
          scripts/package-dmg.sh build-lite-xl-bundle $INSTALL_PREFIX-macos
      - name: Upload Mac Images
        uses: actions/upload-artifact@v3
        with:
          name: macOS Portable and DMGs
          path: |
            *.dmg
            *.tar.gz

  build_windows_msys2:
    name: Windows
    needs: [version]
    runs-on: windows-2019
    strategy:
      matrix:
        config:
          - {msystem: MINGW32, arch: i686}
          - {msystem: MINGW64, arch: x86_64}
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v3
    - uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.config.msystem }}
        install: >-
          base-devel
          git
          zip
          mingw-w64-${{ matrix.config.arch }}-gcc
          mingw-w64-${{ matrix.config.arch }}-meson
          mingw-w64-${{ matrix.config.arch }}-ninja
          mingw-w64-${{ matrix.config.arch }}-ca-certificates
          mingw-w64-${{ matrix.config.arch }}-ntldd
    - name: Set Environment Variables
      run: |
        bash --version
        echo "$HOME/.local/bin" >> "$GITHUB_PATH"
        if [[ "${MSYSTEM}" == "MINGW64" ]]; then
          echo "ARCH=x86_64-windows" >> "$GITHUB_ENV"
          echo "ADDONS=--addons" >> "$GITHUB_ENV"
        else
          echo "ARCH=x86-windows" >> "$GITHUB_ENV"
        fi
    - name: Build
      run: |
        scripts/build.sh $ADDONS -U --debug --forcefallback
    - name: Package Portable
      run: |
        cd build-$ARCH
        zip ../lite-xl-${{ needs.version.outputs.ref }}-$ARCH.zip -r lite-xl
        cd ..
    - name: Package Setup
      run: |
        scripts/package-innosetup.sh --debug --version ${{ needs.version.outputs.ref }}
    - name: Upload Artifacts
      if: ${{ matrix.config.arch == 'x86_64' }}
      uses: actions/upload-artifact@v3
      with:
        name: Windows Portable & Installer
        path: |
          *.zip
          *.exe

  build_windows_msvc:
    name: Windows (MSVC)
    needs: [version]
    runs-on: windows-2019
    strategy:
      matrix:
        arch:
          - { target: x86, name: i686 }
          - { target: x64, name: x86_64 }
    steps:
      - uses: actions/checkout@v3
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch.target }}
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install meson and ninja
        run: |
          pip install meson ninja
      - name: Set up environment variables
        run: |
          "INSTALL_NAME=lite-xl-${{ needs.version.outputs.ref }}-windows-msvc-${{ matrix.arch.name }}" >> $env:GITHUB_ENV
          "LUA_SUBPROJECT_PATH=subprojects/$(awk -F ' *= *' '/directory/ { printf $2 }' subprojects/lua.wrap)" >> $env:GITHUB_ENV
      - name: Download and patch subprojects
        shell: bash
        run: |
          meson subprojects download
          cat resources/windows/001-lua-unicode.diff | patch -Np1 -d "$LUA_SUBPROJECT_PATH"
      - name: Configure
        run: |
          meson setup --wrap-mode=forcefallback build
      - name: Build
        run: |
          meson install -C build --destdir="../lite-xl"
      - name: Package Portable
        run: |
          Remove-Item -Recurse -Force -Path "lite-xl/lib","lite-xl/include"
          Compress-Archive -Path lite-xl -DestinationPath "$env:INSTALL_NAME.zip"

  release:
    name: Create Release
    needs: [version, build_windows_msys2, build_macos, build_linux]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          path: .
      - name: Versioned Release
        uses: softprops/action-gh-release@v1
        if: ${{ needs.version.outputs.release }}
        with:
          tag_name: ${{ needs.version.outputs.release }}
          name: Lite XL ${{ needs.version.outputs.release }}
          draft: true
          body_path: changelog.md
          generate_release_notes: true
          files: |
            */*.tar.gz
            */*.zip
            */*.exe
            */*.dmg
            */*.AppImage
      - name: Update Tag
        uses: richardsimko/update-tag@v1
        if: github.ref == 'refs/heads/master'
        with:
          tag_name: continuous
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Continuous Release
        uses: softprops/action-gh-release@v1
        if: github.ref == 'refs/heads/master'
        with:
          name: Lite XL Continuous Release
          tag_name: continuous
          prerelease: true
          files: |
            */*.tar.gz
            */*.zip
            */*.exe
            */*.dmg
            */*.AppImage
